#!/usr/bin/env bash
# theorysim (JBES theory-validation add-on) -- build the report end to end.
# Runs the experiments, builds figures/tables, the reproducibility appendix, then latexmk.
# QUICK=1 (default) uses modest rep counts for a fast first compile; QUICK=0 uses full counts.
set -euo pipefail

PY=/Users/alessiobrini/anaconda3/envs/tsa-dev/bin/python3
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
REPORT=reports/theory_validation
QUICK="${QUICK:-1}"

if [ "$QUICK" = "1" ]; then
  E1REPS=40; E1GRID="80 160 320"; E2REPS=2000; E3REPS=150; E4OOS=30; E4N=200; E4EP=800; EP=400
else
  E1REPS=100; E1GRID="80 160 320 640 1000"; E2REPS=2000; E3REPS=500; E4OOS=50; E4N=300; E4EP=1200; EP=800
fi

echo "== E1 relative rerun: oracle + parameter_free =="
$PY -m src.theorysim.rerun_e1_relative --reps "$E1REPS" --epochs "$EP" --grid $E1GRID \
    --arms oracle parameter_free --out outputs/theorysim/e1/relative_rerun.csv
echo "== E1 relative rerun: independent_lag (paper-faithful) =="
$PY -m src.theorysim.rerun_e1_relative --reps "$E1REPS" --epochs "$EP" --grid $E1GRID \
    --arms independent_lag --out outputs/theorysim/e1/relative_rerun_lag.csv
echo "== E2 coverage =="
$PY -m src.theorysim.exp_e2_coverage --reps "$E2REPS"
echo "== E3 efficiency =="
$PY -m src.theorysim.exp_e3_efficiency --reps "$E3REPS"
echo "== E4 bridge =="
$PY -m src.theorysim.exp_e4_bridge --N "$E4N" --T "$E4N" --n-oos "$E4OOS" --epochs "$E4EP"
echo "== figures + tables + heatmaps =="
$PY -m src.theorysim.make_report_assets

echo "== reproducibility appendix =="
$PY - "$REPORT/exhibit_manifest.csv" "$REPORT/repro_appendix.tex" <<'PYEOF'
import csv, sys
man, out = sys.argv[1], sys.argv[2]
def esc(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")
def ttbreak(s):
    # escape then allow line breaks after path/command separators so long tokens wrap
    s = esc(s)
    for ch in ("/", ".", r"\_", "-"):
        s = s.replace(ch, ch + r"\allowbreak{}")
    return r"{\tiny\ttfamily " + s + "}"
rows = list(csv.DictReader(open(man)))
with open(out, "w") as f:
    f.write("\\section*{Reproducibility appendix}\n")
    f.write("Every exhibit is regenerated by a committed script.\n\n")
    f.write("{\\scriptsize\\begin{longtable}{p{0.26\\textwidth} p{0.30\\textwidth} p{0.36\\textwidth}}\n")
    f.write("\\toprule Exhibit & Script & Command \\\\\n\\midrule\n\\endhead\n")
    for r in rows:
        f.write(f"{esc(r['exhibit'])} & {ttbreak(r['script'])} & {ttbreak(r['command'])} \\\\\n")
    f.write("\\bottomrule\n\\end{longtable}}\n")
PYEOF

echo "== latexmk =="
cd "$REPORT"
latexmk -pdf -interaction=nonstopmode -halt-on-error report.tex >/dev/null
echo "built: $REPORT/report.pdf"
